# Generated by Django 6.1 on 2026-08-30 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import logs.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("systems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(help_text="Raw log output or Markdown report"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARN", "Warning"),
                            ("ERR", "Error"),
                            ("CRIT", "Critical"),
                        ],
                        default="INFO",
                        max_length=4,
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                (
                    "creator_api_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_logs",
                        to="systems.apientity",
                    ),
                ),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(logs.helpers.get_sentinel_user),
                        related_name="created_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="log_entries", to="logs.logtag"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Log Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(logs.helpers.get_sentinel_user),
                        related_name="created_incident_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="child_notes",
                        to="logs.incidentnote",
                    ),
                ),
                (
                    "log_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="logs.log",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="log",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("creator_api_entity__isnull", True),
                        ("creator_user__isnull", False),
                    ),
                    models.Q(
                        ("creator_api_entity__isnull", False),
                        ("creator_user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_created_by_type_required",
                violation_error_message="Specify exactly one of creator_user and creator_api_entity.",
            ),
        ),
    ]
