# Generated by Django 6.1 on 2026-08-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apientity",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "API Entities",
            },
        ),
    ]
